### PR TITLE
Dev-3871 Platforms > Upgrade node version to latest Active LTS

### PR DESCRIPTION
**Pull request by wilbertverayin**
## Ticket references
- [Dev-3871 Platforms > Upgrade node version to latest Active LTS](https://freedom.myjetbrains.com/youtrack/issue/Dev-3871)

## Summary of changes
update kue-scheduler version to have no warning on node 14

## Checklist

- [x] bugfix
- [ ] new feature
- [ ] breaking change
- [ ] added unit tests
- [ ] changes introduced has been discussed and approved
- [ ] requires manual testing
- [ ] documentation has been updated

## Testing
do regression test kue-based tasks on aegis, upload and earnings
- specific tests areas to follow

### CODE REVIEW

**Review by pandafox — APPROVED** [review]
Any breaking change that we know of?

**Review by cedricabuso — APPROVED** [review]

**Comment by wilbertverayin** [comment]
@pandafox @cedricabuso 
Actually, this still does not fix the warnings

this is the dependency tree of cid even with latest kue scheduler
https://gist.github.com/wilbertverayin/b5d2f0392bc9e72b4bbaf59860c4d8c7

kue-scheduler while the latest kue-scheduler is now dependent on the latest stylus,

it is also dependent on the latest kue, which is dependent on an old version of stylus,

the old version of stylus causes the warnings.

since we cannot really update kue-scheduler and kue, there is no way we can remove the warnings ourselves, well except we change out queue library to another one, for instance, [bull](https://www.npmjs.com/package/bull)

#notsponsored, lol

**Comment by pandafox** [comment]
I agree, as we have not see functional issue with this, let's document and move forward and plan for upgrade to bull.

**Comment by wilbertverayin** [comment]
Closing this PR now as this do not make the warning go away actually.

See discussion on slack thread
https://freedom.slack.com/archives/C1FMBSL3Z/p1628891230025900

**Pull request closed without merging**
